name: CI

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-versions:
          - 26.2
          - 26.3
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-versions }}
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test
